name: Generate Static Site with AsciiDoc

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ruby and Asciidoctor
        run: |
          gem install asciidoctor asciidoctor-pdf

      - name: Process AsciiDoc files
        run: |
          mkdir -p build/site
          asciidoctor -D build/site -R src/docs/asciidoc **/*.adoc

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/site